# !!! Underconstruction !!!

# 0. Import Python libraries

In [160]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sy

# 1. $f$, $\nabla f$ and $\nabla^2 f$ definition

In [161]:
"""This section enables to express f (objective function), its gradient vector and hessian matrix symbolically and evaluate them at specific coordinates.
To do so, express analititically f by indexing the symbolic variable x. For instance x[0] represent first dimension, x[1] the second and so on.
grad_f_exp and hess_f_exp are only there to automatically differentiate f_exp. To evaluate the f, grad_f or hess_f functions, call them precising the desirated coordinates.
This evaluation use lambdify function and uses "numpy" format.

    Parameters
    ----------
    x : sympy.IndexedBase
        symbolic variable managing indexes. For instance, instead of declaring n variable for the n dimensions (x, y, z, ...) which isn't easily scalable, 
        here variables are automaticly indexed (x_1, x_2, ..., x_n).

    xk : np.array (float)
        Coordinates to evaluate the function.

    Returns
    -------
    numpy.float (scalar or numpy.array)
        Depending on the considered function, return a scalar, a (n, ) vector or a (n, n) array.

    Notes
    ------
    The use of specific function to express f, grad_f and hess_f is to improve scalability in the case of not having analitic expression.
    For instance, when only have a black box model which evaluate f, grad_f (and hess_f). 

    References
    ------
    https://docs.sympy.org/latest/index.html

    Examples
    ------
    >>>x = sy.IndexedBase('x')
    >>>xk = [-4, 3]
    >>>dk = grad_f(x, xk)
    """

def f_exp(x):
    return 3*x[0]**2 + 2*x[1]**2 + 20*sy.cos(x[0])*sy.cos(x[1])+40

def f(x, xk):
    return sy.lambdify(x, f_exp(x), "numpy")(xk)

def grad_f_exp(x, xk):
    return [sy.diff(f_exp(x), x[i]) for i in range(len(xk))]

def grad_f(x, xk):
    lambdify = [sy.lambdify(x, gf, "numpy") for gf in grad_f_exp(x, xk)]
    return np.array([lambdify[i](xk) for i in range(len(xk))])

def hess_f_exp(x, xk):
    return [[sy.diff(g, x[i]) for i in range(len(xk))] for g in grad_f_exp(x, xk)]

def hess_f(x, xk):
    lambdify = [[sy.lambdify(x, gf, "numpy") for gf in Hs] for Hs in hess_f_exp(x, xk)]
    return np.array([[lambdify[i][j](xk) for i in range(len(xk))] for j in range(len(xk))])

# 2. PSO

In [73]:
dom = [[0, 4, 5], [2, 5, 4], [-3, -1, 3]]
nx = [np.linspace(dom[i][0], dom[i][1], dom[i][2]) for i in range(len(dom))]
X = [[[[i, j, l] for i in nx[0]] for j in nx[1]] for l in nx[2]]

nxx, nyy = np.meshgrid(nx[0], nx[1])
print(nxx)
print(nyy)
test = zip(nxx[0], nyy[0])
print(list(test))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]
[(0.0, 2.0), (1.0, 2.0), (2.0, 2.0), (3.0, 2.0), (4.0, 2.0)]


In [ ]:
import numpy as np
#[lw_bd, up_bd, nb_val]
domaine = [[0, 4, 10], [2, 5, 10]]

def X_init_uniform(domaine):
        interval = [(dom[1] - dom[0])/dom[2] for dom in domaine]
        X = [[domaine[j][0] + i*interval[j] for i in range(N+1)]for j in range(len(interval))]
        return X

X_init_uniform(domaine)

In [162]:
class PSO():
    def __init__(
        self,
        f,                  #fonction coût
        N,                  #nombre de particules de l'essaim
        domaine,
        *,
        X_init="random",    #plan de recherche initiale (uniforme, aléatoire)
        stop="position",    #critère d'arrêt (position ou f)        
        seed=0,             #random_seed
        w=.95,              #inertie vitesse
        c1=.5,              #comportement cognitif de la particule
        c2=.5,              #Aptitude sociale de la particule
        max_it=50           #nombre d'itération max
        ):
        self.f = f
        self.N = N
        self.domaine = domaine
        self.X_init = X_init
        self.seed = seed
        self.w = w
        self.c1 = c1
        self.c2 = c2
        self.max_it = max_it
    
    def X_init_uniform(PSO):    #uniformément distribué sur les domaines
        X = [(dom[0] + dom[1])/PSO.N for dom in PSO.domaine]
        return X
    
    def X_init_random(PSO):     #aléatoire avec distribution uniforme
        X = [np.random.uniform(dom, PSO.N) for dom in domaine]
        return X
    
    def visualization(PSO):
        print("hello")

    def fit(PSO):
        it =0
        r1 = np.random.rand()
        r2 = np.random.rand()

        #init = {"uniform": PSO.X_init_uniform(PSO), "random": PSO.X_init_random}
        #X = init[PSO.X_init]
        X = [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4],
             [1, 0], [1, 1], [1, 2], [1, 3], [1, 4]
             [2, 0], [2, 1], [2, 2], [2, 3], [2, 4]
             [3, 0], [3, 1], [3, 2], [3, 3], [3, 4]
             [4, 0], [4, 1], [4, 2], [4, 3], [4, 4]]
        x_best = X[0]

        for x in X:
            if x

        G = [np.inf, ]     #set initiale global best
        P = []

        while(it <= PSO.max_it):
            print("hello")
        return G

In [164]:
"""Dans le cas d'une optimisation black box, soit on retire toutes les instances de x 
dans les fonctions, soit on le laisse et on l'utilise pas dans la définition 
de f, grad_f et hes_f
"""
x = sy.IndexedBase('x')

a0 = 15
b = .95
w_1 = .15
max_it = 500

xk = [-4, 3]
dk = - grad_f(x, xk)/np.linalg.norm(grad_f(x, xk))        #dk a unit vector

armijolinesearch = Armijo(x, xk, dk, a0=a0, b=b, w_1=w_1, max_it=max_it)
m, alpha = armijolinesearch.fit()
print(f"m: {m}")
print(f"alpha: {alpha}")
print(f"dk: {dk}")

m: 9
alpha: 9.453741145869136
dk: [ 0.54568069 -0.83799319]
